version: "3.5"

services:
  mc:
    image: itzg/minecraft-server:latest
    ports:
      - 25565:25565
    environment:
      EULA: "true"
      VERSION: "1.19"
      OVERRIDE_SERVER_PROPERTIES: "true"
      MOTD: "Servidor de Minecraft Aqui Pedro"
      DIFFICULTY: "normal"
      ALLOW_NETHER: "true"
      ANNOUNCE_PLAYER_ACHIEVEMENTS: "true"
      FORCE_GAMEMODE: "true"
      GENERATE_STRUCTURES: "true"
      SNOOPER_ENABLED: "false"
      SPAWN_ANIMALS: "true"
      SPAWN_MONSTERS: "true"
      SPAWN_NPCS: "true"
      SPAWN_PROTECTION: "true"
      VIEW_DISTANCE: 10
      MODE: "survival"
      LEVEL_TYPE: "DEFAULT"
      LEVEL: "MUNDO DO PEDRO"
      ONLINE_MODE: "true"
      SERVER_NAME: "Servidor de Minecraft Aqui Pedro"
      SERVER_PORT: 25565
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data